### ISSUE TITLE
Why use pg_try_advisory_lock in a loop?

### ISSUE THREAD

**Issue by samandmoore** [heroku/pg_lock#3]
I came across this gem rather randomly, and it seems to overlap in use-case with some code I've worked on recently. I was pleasantly surprised to run across a gem that was using this feature and baking a really pretty API around it. Please pardon my intrusion.

I guess I have two main questions.
#### 1. Why not use an advisory transaction lock and lean on commit to release?

Advisory transaction locks have these nice properties:
- they releases at the close of a transaction
- they hold the lock until your critical section has completed and no longer, which means they co-transactionally release when you've done whatever mutative things you meant to be doing and your new state-of-the-world is visible to others

Also, if pg_lock used this strategy, and a consumer had a specific desire to unlock the resource before the rest of their database operation commits, then you could easily feed this `Locket` a standalone connection. Obviously, the downside there is that you'd need to have more connections available than you would otherwise.
#### 2. Why use a try lock-acquisition strategy?

A non-try based strategy has these properties:
- they will wait until the lock can be acquired instead of immediately returning false and forcing application code to have to retry.
- they will wait in line for the lock, so you get fairness in the acquisition sequence

In contrast, when using a try-based strategy it seems like your ability to acquire a lock will get worse at higher levels concurrency. You'll spend more time spinning in application code issuing requests for a lock instead of waiting on I/O (possibly allowing another thread to use the CPU).

relevant line of code here: https://github.com/heroku/pg_lock/blob/dc13dfd6476c54ecfed8caac4907db2bc7faadab/lib/pg_lock/locket.rb#L11

I would be interested to know what other drivers there might have been for the trade-offs in this gem.

Thanks!

**Comment by schneems** [comment]
I originally wrote this gem as an extraction of some code that was being run in production, for the purpose of using in another gem. I don't think the production code ever got switched out to use this gem due to it needing a larger scope than I was willing to provide with the gem. It turns out the gem I thought I needed this for didn't need postgres locks after all, so honestly i'm not even using this anymore. It turns out theres **TONS** of postgres locking gems I think https://github.com/mceachen/with_advisory_lock is one of the more popular. 200k downloads compared to this libraries' 500 downloads.
